<?php

namespace Database\Seeders;

use App\Models\WordContractions;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CreateWordContractionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $wordContractions = [
            [
                'contraction'=>"it's",
                'expansion'=>"it,is"
            ],
            [
                'contraction'=>"can't",
                'expansion'=>"can,not"
            ],
            [
                'contraction'=>"wasn't",
                'expansion'=>"was,not"
            ],
            [
                'contraction'=>"ain't",
                'expansion'=>"is,not"
            ],
            [
                'contraction'=>"isn't",
                'expansion'=>"is,not"
            ],
            [
                'contraction'=>"i'm",
                'expansion'=>"i,am"
            ],
            [
                'contraction'=>"you're",
                'expansion'=>"you,are"
            ],
            [
                'contraction'=>"he's",
                'expansion'=>"he,is"
            ],
            [
                'contraction'=>"she's",
                'expansion'=>"she,is"
            ],
            [
                'contraction'=>"we're",
                'expansion'=>"we,are"
            ],
            [
                'contraction'=>"they're",
                'expansion'=>"they,are"
            ],
            [
                'contraction'=>"don't",
                'expansion'=>"do,not"
            ],
            [
                'contraction'=>"won't",
                'expansion'=>"will,not"
            ],
            [
                'contraction'=>"shouldn't",
                'expansion'=>"shouldn't"
            ],
            [
                'contraction'=>"wouldn't",
                'expansion'=>"would,not"
            ],
            [
                'contraction'=>"hasn't",
                'expansion'=>"has,not"
            ],
            [
                'contraction'=>"haven't",
                'expansion'=>"have,not"
            ],
            [
                'contraction'=>"aren't",
                'expansion'=>"are,not"
            ],
            [
                'contraction'=>"weren't",
                'expansion'=>"were,not"
            ],
            [
                'contraction'=>"there's",
                'expansion'=>"there,is"
            ],
            [
                'contraction'=>"there're",
                'expansion'=>"there,are"
            ],
            [
                'contraction'=>"that's",
                'expansion'=>"that,is"
            ],
            [
                'contraction'=>"that're",
                'expansion'=>"that,are"
            ],
            [
                'contraction'=>"who's",
                'expansion'=>"who,is"
            ],
            [
                'contraction'=>"who're",
                'expansion'=>"who,are"
            ],
            [
                'contraction'=>"it'll",
                'expansion'=>"it,will"
            ],
            [
                'contraction'=>"i'll",
                'expansion'=>"i,will"
            ],
            [
                'contraction'=>"you'll",
                'expansion'=>"you,will"
            ],
            [
                'contraction'=>"he'll",
                'expansion'=>"he,will"
            ],
            [
                'contraction'=>"she'll",
                'expansion'=>"she,will"
            ],
            [
                'contraction'=>"we'll",
                'expansion'=>"we,will"
            ],
            [
                'contraction'=>"we've",
                'expansion'=>"we,have"
            ],
            [
                'contraction'=>"they,'ll",
                'expansion'=>"they,will"
            ],
            [
                'contraction'=>"didn't",
                'expansion'=>"did,not"
            ],
            [
                'contraction'=>"i've",
                'expansion'=>"i,have"
            ],
            [
                'contraction'=>"i'd",
                'expansion'=>"i,would"
            ],
            [
                'contraction'=>"you've",
                'expansion'=>"you,have"
            ],
            [
                'contraction'=>"here's",
                'expansion'=>"here,is"
            ],
            [
                'contraction'=>"hadn't",
                'expansion'=>"had,not"
            ],
            [
                'contraction'=>"they've",
                'expansion'=>"they,have"
            ],
            [
                'contraction'=>"you'd",
                'expansion'=>"you,would"
            ],
            [
                'contraction'=>"couldn't",
                'expansion'=>"could,not"
            ],
            [
                'contraction'=>"doesn't",
                'expansion'=>"does,not"
            ],
            [
                'contraction'=>"let's",
                'expansion'=>"let,us"
            ],
            [
                'contraction'=>"she'd",
                'expansion'=>"she,would"
            ],
        ];

        foreach($wordContractions as $wordContraction)
        {
            WordContractions::create($wordContraction);
        }
    }   // end of run()
}   // end of CreateWordContractionsSeeder class
